# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push, pull_request ]

jobs:
  frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    env:
      working_dir: "webapp"

    defaults:
      run:
        working-directory: ${{env.working_dir}}


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: npm run lint
      - run: npm run test

  backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    env:
      working_dir: "backend"

    defaults:
      run:
        working-directory: ${{env.working_dir}}


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install database server
        uses: fehu/Setup-Neo4j@v1.2.0
        with:
          tag: 'latest'

      - run: npm install
      - run: npm run lint
      - run: npm run test:unit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
          NEO4J_USER: ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
